name: Feature request
description: Suggest an idea for this project.
title: "A title for the feature request"
labels: ["feature request"]
body:

  - type: textarea
    id: problemDescription
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
      placeholder: Please input
    validations:
      required: true

  - type: textarea
    id: solutionDescription
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Please input

  - type: textarea
    id: addition
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Please input
